#!/usr/bin/env node
// Post-deploy env sync (#94). Reads the canonical deployment record
// (contracts/deployments/<network>.json) and writes the frontend's .env.local so
// the app's NEXT_PUBLIC_* addresses always match the on-chain core. No manual
// address editing after a redeploy — that step is where core_v4/v5 drift crept in.
//
// Usage:
//   node tools/sync-env.mjs                 # write app/.env.local
//   node tools/sync-env.mjs --check         # exit 1 if .env.local is out of sync (CI)
//   node tools/sync-env.mjs --print         # print the block, write nothing
//   node tools/sync-env.mjs --network celo-mainnet
//
// Only the frontend is written here. The indexer (indexer/ponder.config.ts) and
// the simulator (ajora-sim/.env) take the same addresses — this prints them too.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const args = process.argv.slice(2);
const has = (f) => args.includes(f);
const network = (() => {
  const i = args.indexOf("--network");
  return i >= 0 ? args[i + 1] : "celo-mainnet";
})();

// deployment contract name -> app env var
const ENV_KEYS = {
  PotVault: "NEXT_PUBLIC_POTVAULT_ADDRESS",
  StreakSBT: "NEXT_PUBLIC_STREAKSBT_ADDRESS",
  SprayFaucet: "NEXT_PUBLIC_SPRAYFAUCET_ADDRESS",
  DrawManager: "NEXT_PUBLIC_DRAWMANAGER_ADDRESS",
  CrewRegistry: "NEXT_PUBLIC_CREWREGISTRY_ADDRESS",
};

function loadDeployment() {
  const path = join(REPO_ROOT, "contracts", "deployments", `${network}.json`);
  if (!existsSync(path)) {
    fail(`No deployment record at ${path}`);
  }
  return JSON.parse(readFileSync(path, "utf8"));
}

function buildEnv(dep) {
  const c = dep.contracts ?? {};
  const lines = [
    `# Ajora frontend — generated by tools/sync-env.mjs from`,
    `# contracts/deployments/${network}.json. Do not edit by hand; re-run the sync.`,
    `NEXT_PUBLIC_CHAIN_ID=${dep.chainId}`,
    "",
  ];
  for (const [name, key] of Object.entries(ENV_KEYS)) {
    const addr = c[name]?.address;
    if (addr) lines.push(`${key}=${addr}`);
  }
  return lines.join("\n") + "\n";
}

function fail(msg) {
  console.error(`sync-env: ${msg}`);
  process.exit(1);
}

const dep = loadDeployment();
const env = buildEnv(dep);
const target = join(REPO_ROOT, "app", ".env.local");

if (has("--print")) {
  process.stdout.write(env);
  process.exit(0);
}

if (has("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current.trim() !== env.trim()) {
    fail(`app/.env.local is out of sync with ${network}.json — run: node tools/sync-env.mjs`);
  }
  console.log(`sync-env: app/.env.local matches ${network}.json ✓`);
  process.exit(0);
}

writeFileSync(target, env);
console.log(`sync-env: wrote app/.env.local from ${network}.json (${Object.keys(dep.contracts).length} contracts)`);
console.log("sync-env: the indexer + simulator use the same addresses:");
process.stdout.write(
  env
    .split("\n")
    .filter((l) => l.startsWith("NEXT_PUBLIC_") && l.includes("ADDRESS"))
    .map((l) => "  " + l.replace("NEXT_PUBLIC_", "").replace("_ADDRESS", ""))
    .join("\n") + "\n",
);
